apiVersion: skaffold/v2beta22
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/zookeeper-depl.yaml
      - ./infra/k8s/kafka-depl.yaml
      - ./infra/k8s/producer-depl.yaml
      - ./infra/k8s/consumer-depl.yaml
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: secure-racer-348221
  artifacts:
    - image: melzohery/producer
      context: app1
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './index.js'
    - image: melzohery/consumer
      context: app2
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './index.js'