apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: melzohery/consumer
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-srv
spec:
  selector:
    app: consumer
  ports:
  - port: 5001
    targetPort: 5001
    name: consumer
    protocol: TCP
